//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativeBox.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public long ProductAutoId { get; set; }
        public string ProductName { get; set; }
        public string ProductId { get; set; }
        public string StandardBPO { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string WareHouseName { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Department { get; set; }
        public string HsCode { get; set; }
        public string Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string DisplayOrder { get; set; }
        public string ProductReference { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Currency { get; set; }
        public string ProductImage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
