//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativeBox.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        public long QuotationId { get; set; }
        public string OrderId { get; set; }
        public string ProductName { get; set; }
        public string Variation { get; set; }
        public string ProductReference { get; set; }
        public string Process { get; set; }
        public string QuotationType { get; set; }
        public string ProofingMethod { get; set; }
        public string Specification { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string InvoiceRecipient { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> UniversityId { get; set; }
    }
}
